name: git diff --check

on:
  - pull_request
  - push

jobs:
  check:
    runs-on: ubuntu-latest
    name: git diff --check
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: git diff --check
        uses: joel-coffman/action-git-diff-check@dev/initial
